#include "stdafx.h"
#include <OXInteger.h>
#include "Layout.h"
#include "winplace.h"
#include "Filename.h"

#include "ClearBits.h"
#include "SearchDlg.h"
#include "SeekDlg.h"
#include "BrowseDlg.h"


#include "Options.h"
#include "ClearBitsDlg.h"


#ifndef WM_APPCOMMAND
    // WinUser.h only defines #if(_WIN32_WINNT >= 0x0500)
    // Doesn't hurt to define these for previous Winodws OS's, they will just be ignored
    #define WM_APPCOMMAND 0x0319    
    #define APPCOMMAND_MEDIA_NEXTTRACK        11
    #define APPCOMMAND_MEDIA_PREVIOUSTRACK    12
    #define APPCOMMAND_MEDIA_STOP             13
    #define APPCOMMAND_MEDIA_PLAY_PAUSE       14

    #define FAPPCOMMAND_MASK  0xF000

    #define GET_APPCOMMAND_LPARAM(lParam) ((short)(HIWORD(lParam) & ~FAPPCOMMAND_MASK))
    #define GET_FLAGS_LPARAM(lParam)      (LOWORD(lParam))
    #define GET_KEYSTATE_LPARAM(lParam)   GET_FLAGS_LPARAM(lParam)
#endif



#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif



#define MAX_SOUNDBUF_SIZE	(176400 * 5)		// 5 seconds of CD-quality

enum
{
	ALGO_FIRST,
	ALGO_FIXED = ALGO_FIRST,
	ALGO_VC,					// Generated by VC++ rand() function
	ALGO_CAPI,					// Generated by CAPI (16-bits)
	ALGO_RANDOM_ORG,			// Generated at random.org (16-bits)
	NUM_ALGOS					// must be last
};



/////////////////////////////////////////////////////////////////////////////
// CAboutDlg dialog used for App About

class CAboutDlg : public CDialog
{
public:
	CAboutDlg();

// Dialog Data
	//{{AFX_DATA(CAboutDlg)
	enum { IDD = IDD_ABOUTBOX };
	//}}AFX_DATA

	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CAboutDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:
	//{{AFX_MSG(CAboutDlg)
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

CAboutDlg::CAboutDlg() : CDialog(CAboutDlg::IDD)
{
	//{{AFX_DATA_INIT(CAboutDlg)
	//}}AFX_DATA_INIT
}

void CAboutDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CAboutDlg)
	//}}AFX_DATA_MAP
}

BEGIN_MESSAGE_MAP(CAboutDlg, CDialog)
	//{{AFX_MSG_MAP(CAboutDlg)
		// No message handlers
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()



/////////////////////////////////////////////////////////////////////////////
// CClearBitsDlg dialog

CClearBitsDlg::CClearBitsDlg(CWnd* pParent /*=NULL*/)
	: CDialog(CClearBitsDlg::IDD, pParent)
{
	//{{AFX_DATA_INIT(CClearBitsDlg)
	m_bRandomPlay = FALSE;
	m_strOutputFormat = _T("");
	m_strProgress = _T("");
	//}}AFX_DATA_INIT
	// Note that LoadIcon does not require a subsequent DestroyIcon in Win32
	m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
	m_hWaveOut = NULL;
	ZeroMemory ( &m_wfx, sizeof(m_wfx) );

	m_hProvider = NULL;
	m_nAlgo = ALGO_FIRST;

    m_nCryptoSize = (2 * 8) + (2);
}


BOOL CClearBitsDlg::OpenOutDevice (WAVEFORMATEX *pwfx)
{
	if (!pwfx)		// caller hasn't specified desired format
	{
		// use standard 44.1K/16-bit/stereo PCM format
		WAVEFORMATEX wfStandard;
		wfStandard.wFormatTag = WAVE_FORMAT_PCM ;
		wfStandard.wBitsPerSample = 16 ;
		wfStandard.nChannels = 2 ;
		wfStandard.nSamplesPerSec = 44100;
		wfStandard.nAvgBytesPerSec = wfStandard.nSamplesPerSec * wfStandard.nChannels * (wfStandard.wBitsPerSample / 8);	// e.g. 176400
		wfStandard.nBlockAlign = (wfStandard.wBitsPerSample / 8) * wfStandard.nChannels;	// e.g. 4
		wfStandard.cbSize = 0;

		pwfx = &wfStandard;
	}

	if (m_hWaveOut)	// already playing
	{
		// Do nothing unless desired output format has changed
		if ( memcmp ( pwfx, &m_wfx, sizeof(m_wfx) ) == 0 )	// same
			return TRUE;

		// Desired wave format is different; close device and re-open it
		if ( !CloseOutDevice(FALSE) )
			return FALSE;
	}

	CString strCmdLine ( AfxGetApp()->m_lpCmdLine );
	strCmdLine.MakeUpper();
	BOOL bDirect = strCmdLine.Find ("WAVE_FORMAT_DIRECT") >= 0;

	UINT uDeviceId = WAVE_MAPPER;
	int i = strCmdLine.Find ("DEVICE");
	if ( i >= 0 )
	{
		uDeviceId = atoi ( ((LPCTSTR) strCmdLine) + i + 6 );
		CString strMsg;
		strMsg.Format ("Opening device %d", uDeviceId);
		AfxMessageBox (strMsg);
	}

	DWORD fdwOpen = CALLBACK_WINDOW;
	if (bDirect)
	{
		fdwOpen |= WAVE_FORMAT_DIRECT;
		AfxMessageBox ("Opening device with WAVE_FORMAT_DIRECT");
	}

	MMRESULT result = waveOutOpen (&m_hWaveOut, uDeviceId, pwfx, (DWORD_PTR) GetSafeHwnd(), NULL, fdwOpen);	// ASSUME Wave Mapper device is OK
	if (result != MMSYSERR_NOERROR)
	{
		CString str;
		waveOutGetErrorText (result, str.GetBuffer(256), 256);
		str.ReleaseBuffer();
		MessageBox (str, "Output Error", MB_OK) ;
		return FALSE;
	}


	// remember the format of just-opened wave device
	m_wfx = *pwfx;


	m_strOutputFormat.Format ( "%d KHz / %d bit / %s", pwfx->nSamplesPerSec / 1000, pwfx->wBitsPerSample, ((pwfx->nChannels == 2) ? "Stereo" : "Mono") );
	UpdateData (FALSE);

	return TRUE;
}


BOOL CClearBitsDlg::CloseOutDevice (BOOL bCloseImmediately) 
{
	if ( !m_hWaveOut )	// device not open
		return TRUE;

	MMRESULT result;
	if (bCloseImmediately)
	{
		// Stop playing all buffers; because m_hWaveOut is NULL, PlayBuffer()
		// will not pass empty buffers to waveOutWrite() when they are returned to the app
		HWAVEOUT hWaveOutTemp = m_hWaveOut;
		m_hWaveOut = NULL;
		Stop();

		result = waveOutClose (hWaveOutTemp);

		// Restore m_hWaveOut in case waveOutClose() failed; 
		if (result != MMSYSERR_NOERROR)
			m_hWaveOut = hWaveOutTemp;
	}
	else	// wait until all buffers have been played before closing device
	{
		// Attempt to close output device; if buffers
		// are still playing, wait a bit, then try again
		do
		{
			result = waveOutClose (m_hWaveOut);
			if ( result == WAVERR_STILLPLAYING )
				Sleep (500);
		} while ( result == WAVERR_STILLPLAYING );

	}


	ASSERT (result == MMSYSERR_NOERROR);
	if ( result != MMSYSERR_NOERROR )
		return FALSE;

	m_hWaveOut = NULL;

	m_strOutputFormat.Empty();
	UpdateData (FALSE);

	return TRUE;
}



LONG CClearBitsDlg::GetNextBufSize()
{
	// The buffer size starts at 2 seconds.  CD Quality ==> (2 * 176.4 KB = 352.8 KB)
	// Added to that is a random number of samples from 0-64KB.  CD Quality ==> each sample has 4 bytes
	// Therefore each buffer size ranges from 352.8 KB to (352.8 KB + (64 KB * 4)) = 608.8 KB

	LONG lBufSize;
	switch (m_nAlgo)
	{
		case ALGO_FIXED:
			lBufSize = GetNextBufSize_Fixed();
			break;

		case ALGO_VC:
			lBufSize = GetNextBufSize_VC();
			break;

		case ALGO_CAPI:
			lBufSize = GetNextBufSize_CAPI();
			break;

		case ALGO_RANDOM_ORG:
			lBufSize = GetNextBufSize_RandomOrg();
			break;

		default:
			ASSERT (FALSE);
			break;
	}

	return lBufSize;
}


LONG CClearBitsDlg::GetNextBufSize_Fixed()
{
	// Fixed buffer size is 2 seconds + 0.5(max random sample)
	WORD wSample = 0x8000;
	LONG lBufSize = (m_wfx.nAvgBytesPerSec * 2) + (wSample * m_wfx.nBlockAlign);
	return lBufSize;
}



LONG CClearBitsDlg::GetNextBufSize_VC()
{
	// rand() returns 0 - 0x7ffff, these will be 15 most significant bits
	// Call rand() again, the least significant bit will be the least significant bit of wSample
	WORD wSample = ( rand() << 1 ) | ( rand() & 0x0001 );

	LONG lBufSize = (m_wfx.nAvgBytesPerSec * 2) + (wSample * m_wfx.nBlockAlign);
	return lBufSize;
}



LONG CClearBitsDlg::GetNextBufSize_CAPI()
{
	// Call CryptGenRandom(), which uses wSample's initial value as a salt.
	// Set the salt to 0 (no saltiness) which should yield less random results.
	WORD wSample = 0;
	ASSERT (m_hProvider);
	ASSERT (sizeof(wSample) == 2);
	VERIFY ( CryptGenRandom(m_hProvider, sizeof(wSample), (BYTE *) &wSample) );

	LONG lBufSize = (m_wfx.nAvgBytesPerSec * 2) + (wSample * m_wfx.nBlockAlign);
	return lBufSize;
}



LONG CClearBitsDlg::GetNextBufSize_RandomOrg()
{
	// Get 16 bit random number from file generated by random.org
	WORD wSample;
	CFile *pFile;
	pFile = &m_fileRandomData;

	if ( pFile->Read (&wSample, sizeof(wSample)) < sizeof(wSample) )
	{
		// Read failed, perhaps at end of file; read again from beginning
		pFile->SeekToBegin();
		VERIFY ( pFile->Read (&wSample, sizeof(wSample)) ==  sizeof(wSample) );
	}

	// Swap low/high bytes
	wSample = MAKEWORD (HIBYTE(wSample), LOBYTE(wSample));

	LONG lBufSize = (m_wfx.nAvgBytesPerSec * 2) + (wSample * m_wfx.nBlockAlign);

	return lBufSize;
}



void CClearBitsDlg::PlayBuffer (CSampleBuffer *pSB)
{
	if ( m_hWaveOut )
	{
		static LONG lLastBufSize = 0;
		LONG lBufSize;
		lLastBufSize = lBufSize = GetNextBufSize();

		ASSERT ( lBufSize < MAX_SOUNDBUF_SIZE );

		pSB->UnprepareOut (m_hWaveOut);
		pSB->PrepareOut (m_hWaveOut, lBufSize);

		LONG lBytesFilled = 0;

		if (m_WaveReader.IsOpen())
		{
			if (m_WaveReader.Read (lBufSize, (LPBYTE) pSB->m_pData, (DWORD *) &lBytesFilled))
			{
				if (lBytesFilled < lBufSize)	// could not read from current file or finished reading current file
				{
					if (NextFile(FALSE) && Play(FALSE))
					{
						// read from next file
						LONG lBytesFilled2;
						if (m_WaveReader.Read (lBufSize - lBytesFilled, (LPBYTE) (pSB->m_pData + lBytesFilled), (DWORD *) &lBytesFilled2))
							lBytesFilled += lBytesFilled2;
					}
				}

				COXInteger oxProgress ( m_WaveReader.GetProgress() );
				m_strProgress = oxProgress.GetStringNumber (10, TRUE);
				UpdateData (FALSE);
			}
		}

		// Fill remainder of buffer with zeroes
		if ( lBytesFilled < lBufSize )
			ZeroMemory ( pSB->m_pData + lBytesFilled, lBufSize - lBytesFilled );

		// Play it
		MMRESULT result = waveOutWrite (m_hWaveOut, pSB->m_pWaveHdr, sizeof (WAVEHDR)) ;
		ASSERT (result == MMSYSERR_NOERROR);
	}
}													   


BOOL CClearBitsDlg::Play (BOOL bPlayImmediately) 
{
    int nSel = m_lbWaveFiles.GetCurSel();

	if (m_WaveReader.IsOpen() || (m_lbWaveFiles.GetCount() == 0) || (nSel < 0))	// already playing, no files to play, or no selected file
		return TRUE;			// nothing to do

	CString strCurFile;
	m_lbWaveFiles.GetText (nSel, strCurFile);

	// DC HACK:  Remove number at beginning
	if (isdigit(strCurFile[0]))
	{
		int iDot = strCurFile.Find ('.');
		if ( (iDot >= 0) && (iDot <= 4) )
			strCurFile = strCurFile.Mid ( iDot + 2 );
	}

	if ( m_PauseInfo.IsValid() && (m_PauseInfo.m_strFile != strCurFile) )	// user has selected to play another file
	{
		// PauseInfo is antiquated because it relates to another file, ignore it
		m_PauseInfo.Reset();
	}

	if ( !m_WaveReader.Open (	(LPSTR) (LPCSTR) strCurFile ) )
	{
		CString str;
		str.Format ( "Unable to open file %s", (LPCSTR) strCurFile );
		AfxMessageBox (str);
		return FALSE;

		m_strProgress = "0";
		UpdateData (FALSE);
	}

	// Restore Paused position if it is still valid
	if ( m_PauseInfo.IsValid() )
		m_WaveReader.Seek (m_PauseInfo.m_lCurPos);

	// Ensure output device is opened to play the format of this file:
	if ( OpenOutDevice (m_WaveReader.GetWaveFormat()) )
	{
		if (bPlayImmediately)
		{
			if (m_hWaveOut)
				waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately
		}
	}

	GetDlgItem(IDC_BUTTON_PLAYPAUSE)->SetWindowText ( _T("&Pause") );

	return TRUE;
}


void CClearBitsDlg::CloseFile() 
{
	m_WaveReader.Close();

	m_strProgress.Empty();
	UpdateData (FALSE);
}




void CClearBitsDlg::Pause() 
{
	// Save currently playing file and position so when Play is pressed again,
	// we can restore it and start playing from this spot.
	CString strFile = m_WaveReader.GetFileName();
	long lPos = m_WaveReader.GetProgress();

	Stop();

	// Stop() overwrites m_PauseInfo(), restore it with saved values
	m_PauseInfo.Set (strFile, lPos);
}


void CClearBitsDlg::Stop() 
{
	CloseFile();

	if (m_hWaveOut)
		waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately

	// Not paused, reset PauseInfo so nothing is restored when Play is pressed
	m_PauseInfo.Reset();

	GetDlgItem(IDC_BUTTON_PLAYPAUSE)->SetWindowText ( _T("&Play") );
}



BOOL CClearBitsDlg::NextFile (BOOL bPermitRandom)
{
	UpdateData();

	CloseFile();

	UINT nFiles = m_lbWaveFiles.GetCount();
	if ( nFiles == 0 )	// no files
		return FALSE;

    DWORD dwSel;
    BOOL bCtrlKeyPressed = ( (GetKeyState(VK_CONTROL) & 0x8000) != 0 );
	if ( bPermitRandom && (m_bRandomPlay || bCtrlKeyPressed) )
	{
		dwSel = (rand() * (DWORD) nFiles) / RAND_MAX;
	}
	else	// sequential play
	{
		dwSel = m_lbWaveFiles.GetCurSel() + 1;
		if (dwSel >= nFiles )	// played last file
			dwSel = 0;
	}

	m_lbWaveFiles.SetCurSel (dwSel);
	return TRUE;
}

BOOL CClearBitsDlg::PrevFile ()
{
	CloseFile();
	int iSel = m_lbWaveFiles.GetCurSel() - 1;
	if (iSel < 0)	// played first file
		return FALSE;

	m_lbWaveFiles.SetCurSel (iSel);
	return TRUE;
}



BOOL CClearBitsDlg::AddToPlayList (LPCTSTR pFilename)
{
	BOOL bOK = TRUE;

	// Open the file
	CString strFilename (pFilename);
	CFileName fn (strFilename);
	if ( fn.GetExt().CompareNoCase(_T(".m3u")) == 0 )	// MP3 playlist specified
	{
		// Add all wave files listed in playlist
		m_strPlaylistFile.Empty();
		DWORD dwNum = 0;

		TRY
		{
			CStdioFile filePL ( (LPCSTR) fn, CFile::modeRead | CFile::shareDenyWrite );	// play list file
			while (filePL.ReadString (strFilename))
			{
				if ( !strFilename.IsEmpty() && strFilename[0] != '\r' && strFilename[0] != '\n')	// meaningful filename
				{
					CString str;
					str.Format ( _T("%d. %s"), ++dwNum, (LPCSTR) strFilename );
					m_lbWaveFiles.AddString (str);
				}
			}
		}

		CATCH (CFileException, e)
		{
			bOK = FALSE;
		}

		END_CATCH

		m_strPlaylistFile = (LPCTSTR) fn;	// init when successfully read play list
	}
	else	// Wave file specified
	{
		m_lbWaveFiles.AddString (fn);
	}

	m_lbWaveFiles.SetFocus();

	return bOK;
}




void CClearBitsDlg::SetAlgo (UINT nNewAlgo)
{
	ASSERT ( nNewAlgo <= NUM_ALGOS );
	if (m_nAlgo != nNewAlgo )
	{
		m_nAlgo = nNewAlgo;

		if (m_hWaveOut)
			waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately
	}
}



void CClearBitsDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CClearBitsDlg)
	DDX_Control(pDX, IDC_STATIC_TITLE, m_staticTitle);
	DDX_Control(pDX, IDC_LIST_WAVEFILES, m_lbWaveFiles);
	DDX_Control(pDX, IDC_STATIC_LOAD, m_hlLoad);
	DDX_Control(pDX, IDC_STATIC_CLEAR, m_hlClear);
	DDX_Control(pDX, IDC_STATIC_DELETE, m_hlDel);
	DDX_Control(pDX, IDC_STATIC_MOVEFILE, m_hlMove);
	DDX_Check(pDX, IDC_CHECK_RANDOM, m_bRandomPlay);
	DDX_Text(pDX, IDC_STATIC_OUTPUT_FORMAT, m_strOutputFormat);
	DDX_Text(pDX, IDC_STATIC_PROGRESS, m_strProgress);
	//}}AFX_DATA_MAP
	DDX_Control(pDX, IDC_COMBO_ALGO, m_cbAlgo);
	DDX_CBIndex(pDX, IDC_COMBO_ALGO, m_nAlgo);
}

BEGIN_MESSAGE_MAP(CClearBitsDlg, CDialog)
	//{{AFX_MSG_MAP(CClearBitsDlg)
	ON_WM_SYSCOMMAND()
	ON_WM_PAINT()
	ON_WM_QUERYDRAGICON()
	ON_BN_CLICKED(IDC_STATIC_LOAD, OnButtonLoad)
	ON_BN_CLICKED(IDC_BUTTON_PLAYPAUSE, OnButtonPlayPause)
	ON_WM_DESTROY()
	ON_BN_CLICKED(IDC_BUTTON_NEXT, OnButtonNext)
	ON_BN_CLICKED(IDC_BUTTON_PREV, OnButtonPrev)
	ON_LBN_DBLCLK(IDC_LIST_WAVEFILES, OnDblclkListWavefiles)
	ON_LBN_SELCHANGE(IDC_LIST_WAVEFILES, OnSelchangeListWavefiles)
	ON_BN_CLICKED(IDC_BUTTON_SEARCH, OnButtonSearch)
	ON_BN_CLICKED(IDC_CHECK_RANDOM, OnCheckRandom)
	ON_BN_CLICKED(IDC_SEEK_BACK_FAST, OnSeekBackFast)
	ON_BN_CLICKED(IDC_SEEK_BACK_SLOW, OnSeekBackSlow)
	ON_BN_CLICKED(IDC_SEEK_FORWARD_SLOW, OnSeekForwardSlow)
	ON_BN_CLICKED(IDC_SEEK_FORWARD_FAST, OnSeekForwardFast)
	ON_BN_CLICKED(IDC_STATIC_PROGRESS, OnStaticProgress)
	ON_WM_DROPFILES()
	ON_BN_CLICKED(IDC_STATIC_CLEAR, OnButtonClear)
	ON_BN_CLICKED(IDC_STATIC_DELETE, OnButtonDelete)
	ON_BN_CLICKED(IDC_STATIC_MOVEFILE, OnButtonMove)
	ON_WM_QUERYNEWPALETTE()
	ON_WM_PALETTECHANGED()
	ON_WM_SIZE()
	//}}AFX_MSG_MAP
	ON_MESSAGE (MM_WOM_DONE, OnBufPlayed)
    ON_MESSAGE (WM_APPCOMMAND, OnAppCommand)
	ON_CBN_SELCHANGE(IDC_COMBO_ALGO, &CClearBitsDlg::OnCbnSelchangeComboAlgo)
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CClearBitsDlg message handlers

BOOL CClearBitsDlg::OnInitDialog()
{
	CDialog::OnInitDialog();

	// Add "About..." menu item to system menu.

	// IDM_ABOUTBOX must be in the system command range.
	ASSERT((IDM_ABOUTBOX & 0xFFF0) == IDM_ABOUTBOX);
	ASSERT(IDM_ABOUTBOX < 0xF000);

	CMenu* pSysMenu = GetSystemMenu(FALSE);
	if (pSysMenu != NULL)
	{
		CString strAboutMenu;
		strAboutMenu.LoadString(IDS_ABOUTBOX);
		if (!strAboutMenu.IsEmpty())
		{
			pSysMenu->AppendMenu(MF_SEPARATOR);
			pSysMenu->AppendMenu(MF_STRING, IDM_ABOUTBOX, strAboutMenu);
		}
	}

	// Set the icon for this dialog.  The framework does this automatically
	//  when the application's main window is not a dialog
	SetIcon(m_hIcon, TRUE);			// Set big icon
	SetIcon(m_hIcon, FALSE);		// Set small icon

	// 256 color logo	
	m_LogoDibWnd.SetDib (AfxGetResourceHandle(), IDB_LOGO, TRUE);
	VERIFY (m_LogoDibWnd.SubclassDlgItem (IDC_STATIC_LOGO, this));
	
	// Static text controls bolded
	LOGFONT lf;							   
	VERIFY (m_staticTitle.GetTextLogFont(&lf));
	lf.lfWeight = FW_BOLD;
	m_fontBold.CreateFontIndirect (&lf);
	VERIFY (m_staticTitle.SetTextFont(&m_fontBold));

	SetAlgo (ALGO_FIRST);

	DragAcceptFiles();

	m_WaveReader.Create();

	// Init buffer sizing
	// Seed the random number generator
	srand( (unsigned)time( NULL ) );
	
	VERIFY ( CryptAcquireContext(&m_hProvider, 0, 0, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT) );
    if ( !m_hProvider )
        AfxMessageBox (_T("Warning:  Could not initialize ClearBits subsystem (internal error 1"));


	if ( !m_fileRandomData.LoadFromResource (AfxGetResourceHandle(), IDR_BIN_RANDOM_DATA, _T("BIN")) )
        AfxMessageBox (_T("Warning:  Could not initialize ClearBits subsystem (internal error 2"));


	// Prepare output device and buffers for playing
	OpenOutDevice(NULL);
	ASSERT (m_hWaveOut);
	int i;
	for (i=0; i < NUM_SAMPLE_BUFFERS; i++)
	{
		m_arrSB[i].Alloc (MAX_SOUNDBUF_SIZE);	
	}

	for (i=0; i < NUM_SAMPLE_BUFFERS; i++)
		PlayBuffer (&m_arrSB[i]);


	// Load window position from profile
	CWindowPlacement wp;
	wp.Restore( _T("WindowPos"), this );
	
	return TRUE;  // return TRUE  unless you set the focus to a control
}


// If you add a minimize button to your dialog, you will need the code below
//  to draw the icon.  For MFC applications using the document/view model,
//  this is automatically done for you by the framework.

void CClearBitsDlg::OnPaint() 
{
	if (IsIconic())
	{
		CPaintDC dc(this); // device context for painting

		SendMessage(WM_ICONERASEBKGND, (WPARAM) dc.GetSafeHdc(), 0);

		// Center icon in client rectangle
		int cxIcon = GetSystemMetrics(SM_CXICON);
		int cyIcon = GetSystemMetrics(SM_CYICON);
		CRect rect;
		GetClientRect(&rect);
		int x = (rect.Width() - cxIcon + 1) / 2;
		int y = (rect.Height() - cyIcon + 1) / 2;

		// Draw the icon
		dc.DrawIcon(x, y, m_hIcon);
	}
	else
	{
		CDialog::OnPaint();
	}
}

// The system calls this to obtain the cursor to display while the user drags
//  the minimized window.
HCURSOR CClearBitsDlg::OnQueryDragIcon()
{
	return (HCURSOR) m_hIcon;
}



LRESULT CClearBitsDlg::OnBufPlayed (WPARAM, LPARAM lParam)
{
	WAVEHDR *pWaveHdr = (WAVEHDR *) lParam;
	if (pWaveHdr->dwFlags & WHDR_DONE)
	{
		// We're done with this sample buffer
		PlayBuffer ( (CSampleBuffer *) pWaveHdr->dwUser );
	}

	return 0;
}



LRESULT CClearBitsDlg::OnAppCommand (WPARAM, LPARAM lParam)
{
    BOOL bHandled;
    int cmd = GET_APPCOMMAND_LPARAM(lParam);
    switch (cmd)
    {
        case APPCOMMAND_MEDIA_PLAY_PAUSE:
        {
            DWORD dwKeys = GET_KEYSTATE_LPARAM(lParam);
            BOOL bControlKeyPressed = dwKeys & MK_CONTROL;
            _OnButtonPlayPause (bControlKeyPressed);
            bHandled = TRUE;
            break;
        }
        
        case APPCOMMAND_MEDIA_STOP:
        {
            _OnButtonPlayPause (TRUE);
            bHandled = TRUE;
            break;
        }

        case APPCOMMAND_MEDIA_PREVIOUSTRACK:
        {
            OnButtonPrev();
            bHandled = TRUE;
            break;
        }

        case APPCOMMAND_MEDIA_NEXTTRACK:
        {
            OnButtonNext();
            bHandled = TRUE;
            break;
        }
        
        default:
            bHandled = FALSE;
            break;
    }

    return bHandled;
}

void CClearBitsDlg::OnButtonLoad() 
{
	CString strFilename;
	OPENFILENAME ofn;
	ZeroMemory ( &ofn, sizeof(ofn) );
	ofn.lStructSize = sizeof(ofn);
	ofn.hwndOwner = GetSafeHwnd();
	ofn.lpstrFilter = _T("Playlists (*.m3u)\0*.m3u\0Wave Files (*.wav)\0*.wav\0MP3 Files (*.mp3)\0*.mp3\0All Files (*.*)\0*.*\0\0");
	ofn.nFilterIndex = 1;	// first string in lpstrFilter
	ofn.lpstrFile = strFilename.GetBuffer(MAX_PATH);
	ofn.nMaxFile = MAX_PATH;
	ofn.Flags = OFN_ENABLESIZING | OFN_HIDEREADONLY | OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST;
	DWORD dwErr;
	if ( !GetOpenFileName(&ofn) && ( (dwErr = CommDlgExtendedError()) != 0 ) )
	{
		CString str;
		str.Format ("Could not display Open File dialog (error %d)", dwErr);
		AfxMessageBox (str);
	}

	strFilename.ReleaseBuffer();
	if (strFilename.IsEmpty())	// no filename specified
		return;


	// File now being played might not be in the new list so stop playback
	Stop();

	// Clear existing playlist
	OnButtonClear();

	if ( !AddToPlayList (strFilename) )
	{
		AfxMessageBox ( _T("Error loading play list") );
	}
}



void CClearBitsDlg::SavePlaylist() 
{
	if ( m_strPlaylistFile.IsEmpty() )
	{
		// prompt user for playlist file
		OPENFILENAME ofn;
		ZeroMemory ( &ofn, sizeof(ofn) );
		ofn.lStructSize = sizeof(ofn);
		ofn.hwndOwner = GetSafeHwnd();
		ofn.lpstrFilter = _T("Playlists (*.m3u)\0*.m3u\0\0");
		ofn.nFilterIndex = 1;	// first string in lpstrFilter
		ofn.lpstrFile = m_strPlaylistFile.GetBuffer(MAX_PATH);
		ofn.lpstrDefExt = _T(".m3u");
		ofn.nMaxFile = MAX_PATH;
		ofn.Flags = OFN_ENABLESIZING | OFN_HIDEREADONLY;
		DWORD dwErr;
		if ( !GetOpenFileName(&ofn) && ( (dwErr = CommDlgExtendedError()) != 0 ) )
		{
			CString str;
			str.Format ("Could not display Open File dialog (error %d)", dwErr);
			AfxMessageBox (str);
		}

		m_strPlaylistFile.ReleaseBuffer();
	}

	// Write all files listed in playlist
	if (!m_strPlaylistFile.IsEmpty())
	{
		// File now being played might not be in the new list so stop playback
		Stop();

		TRY
		{
			CStdioFile filePL (m_strPlaylistFile, CFile::modeWrite | CFile::modeCreate | CFile::shareExclusive );	// play list file
			CString strCurFile;
			for (int i=0; i < m_lbWaveFiles.GetCount(); i++)
			{
				m_lbWaveFiles.GetText (i, strCurFile);

				// DC HACK:  Remove number at beginning
				if (isdigit(strCurFile[0]))
				{
					int iDot = strCurFile.Find ('.');
					if ( (iDot >= 0) && (iDot <= 4) )
						strCurFile = strCurFile.Mid ( iDot + 2 );
				}

				filePL.WriteString (strCurFile);
				filePL.WriteString ("\n");
			}
		}

		CATCH (CFileException, e)
		{
			AfxMessageBox ( _T("Error saving play list") );
		}

		END_CATCH
	}
}


	
void CClearBitsDlg::OnButtonClear() 
{
	// File now being played is not in the new list so stop playback
	Stop();

	m_lbWaveFiles.ResetContent();

	m_strPlaylistFile.Empty();	// no play list; reset filename


	m_lbWaveFiles.SetFocus();
}


void CClearBitsDlg::OnDblclkListWavefiles() 
{
	Stop();
	Play (TRUE);		// Start playback at current file
}

void CClearBitsDlg::OnSelchangeListWavefiles() 
{
	BOOL bIsPlaying = m_WaveReader.IsOpen();

	Stop();		// stop playback of whatever file is being played

	if (bIsPlaying)
		Play (TRUE);		// Start playback at current file
}



void CClearBitsDlg::_OnButtonPlayPause (BOOL bCtrlKeyPressed) 
{
	if ( m_WaveReader.IsOpen() )
	{
		if (bCtrlKeyPressed)
			Stop();
		else
			Pause();
	}
	else
		Play (TRUE);

	m_lbWaveFiles.SetFocus();
}



void CClearBitsDlg::OnButtonPlayPause() 
{
    BOOL bCtrlKeyPressed = ( (GetKeyState(VK_CONTROL) & 0x8000) != 0 );
    _OnButtonPlayPause (bCtrlKeyPressed);
}



void CClearBitsDlg::OnButtonNext() 
{
	BOOL bIsPlaying = m_WaveReader.IsOpen();
	Stop();
	if ( NextFile(TRUE) )
	{
		if (bIsPlaying)
			Play (TRUE);
	}

	m_lbWaveFiles.SetFocus();
}

void CClearBitsDlg::OnButtonPrev() 
{
	BOOL bIsPlaying = m_WaveReader.IsOpen();
	Stop();
	if (PrevFile())
	{
		if (bIsPlaying)
			Play (TRUE);
	}

	m_lbWaveFiles.SetFocus();
}



void CClearBitsDlg::OnButtonSearch() 
{
	CSearchDlg dlg;
	if ( (dlg.DoModal() == IDOK) && (dlg.m_nSelectedFile >= 0) )
	{
		Stop();		// stop playback of whatever file is being played

		m_lbWaveFiles.SetCurSel ( dlg.m_nSelectedFile );

		Play (TRUE);		// Start playback at current file
	}

	m_lbWaveFiles.SetFocus();
}



void CClearBitsDlg::OnDestroy() 
{
	// ASSUME this is called no matter how program is ended
	CDialog::OnDestroy();

	DragAcceptFiles(FALSE);

	Stop();

    for (UINT i=0; i < NUM_SAMPLE_BUFFERS; i++)
        m_arrSB[i].UnprepareOut(m_hWaveOut);

	CloseOutDevice (TRUE);

	if (m_hProvider)
		CryptReleaseContext(m_hProvider, 0);

	// Save current window placement in registry
	CWindowPlacement wp;
	wp.Save( _T("WindowPos"), this);
}

void CClearBitsDlg::OnSysCommand(UINT nID, LPARAM lParam)
{
	if ((nID & 0xFFF0) == IDM_ABOUTBOX)
	{
		CAboutDlg dlgAbout;
		dlgAbout.DoModal();
	}
	else if ( nID == SC_CLOSE )
	{
		// Just clicking on 'X' in caption bar does not cause program to terminate!
		PostMessage (WM_CLOSE);
	}
	else
	{
		CDialog::OnSysCommand(nID, lParam);
	}
}



void CClearBitsDlg::OnCheckRandom() 
{
	UpdateData();
	m_lbWaveFiles.SetFocus();
}



void CClearBitsDlg::OnButtonDelete() 
{
	BOOL bShiftKeyPressed = ( (GetKeyState(VK_SHIFT) & 0x8000) != 0 );
	if (bShiftKeyPressed)
		DeleteFileFromDisk();
	else
		DeleteFileFromPlaylist();
}



void CClearBitsDlg::DeleteFileFromPlaylist() 
{
    int nSel = m_lbWaveFiles.GetCurSel();
	if ( (m_lbWaveFiles.GetCount() > 0) && (nSel >= 0))	// selected file
	{
		BOOL bIsPlaying = m_WaveReader.IsOpen();
		Stop();
		
		// delete from listbox
		m_lbWaveFiles.DeleteString (nSel);
		
		// Save playlist
		SavePlaylist();
		
		if (nSel >= m_lbWaveFiles.GetCount())
			nSel = m_lbWaveFiles.GetCount();
		
		// Select next file in list
		if (nSel >= 0)	// valid selection
		{
			m_lbWaveFiles.SetCurSel (nSel);
			
			// Resume playback
			if (bIsPlaying)
				Play (TRUE);
		}
	}
	
	m_lbWaveFiles.SetFocus();
}

void CClearBitsDlg::DeleteFileFromDisk() 
{
    int nSel = m_lbWaveFiles.GetCurSel();
	if ( (m_lbWaveFiles.GetCount() > 0) && (nSel >= 0))	// selected file
	{
		CString strCurFile;
		m_lbWaveFiles.GetText (nSel, strCurFile);

		// DC HACK:  Remove number at beginning
		if (isdigit(strCurFile[0]))
		{
			int iDot = strCurFile.Find ('.');
			if ( (iDot >= 0) && (iDot <= 4) )
				strCurFile = strCurFile.Mid ( iDot + 2 );
		}

		CString strMsg;
		strMsg.Format ("Really delete file\n%s?", (LPCTSTR) strCurFile);
		if ( AfxMessageBox (strMsg, MB_YESNO | MB_ICONQUESTION) == IDYES )
		{
			// delete from playlist
			DeleteFileFromPlaylist();

			// delete from disk
			if ( !DeleteFile (strCurFile) )
			{
				strMsg.Format ("Could not delete\n%s", (LPCTSTR) strCurFile);
				AfxMessageBox (strMsg);
			}
		}
	}

	m_lbWaveFiles.SetFocus();
}


void CClearBitsDlg::OnSeekBackFast() 
{
	m_WaveReader.Seek ( m_WaveReader.GetProgress() - m_WaveReader.GetWaveFormat()->nAvgBytesPerSec * 60 );
	if (m_hWaveOut)
		waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately

	m_lbWaveFiles.SetFocus();
}

void CClearBitsDlg::OnSeekBackSlow() 
{
	m_WaveReader.Seek ( m_WaveReader.GetProgress() - m_WaveReader.GetWaveFormat()->nAvgBytesPerSec * 10 );
	if (m_hWaveOut)
		waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately

	m_lbWaveFiles.SetFocus();
}

void CClearBitsDlg::OnSeekForwardSlow() 
{
	m_WaveReader.Seek ( m_WaveReader.GetProgress() + m_WaveReader.GetWaveFormat()->nAvgBytesPerSec * 10 );
	if (m_hWaveOut)
		waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately

	m_lbWaveFiles.SetFocus();
}

void CClearBitsDlg::OnSeekForwardFast() 
{
	m_WaveReader.Seek ( m_WaveReader.GetProgress() + m_WaveReader.GetWaveFormat()->nAvgBytesPerSec * 60 );
	if (m_hWaveOut)
		waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately

	m_lbWaveFiles.SetFocus();
}

void CClearBitsDlg::OnStaticProgress() 
{
	CSeekDlg dlg;
	if (dlg.DoModal() == IDOK)
	{
		m_WaveReader.Seek ( atoi (dlg.m_strSeekPos) );
		if (m_hWaveOut)
			waveOutReset (m_hWaveOut);	// force callback to fill bufs with data immediately
	}

	m_lbWaveFiles.SetFocus();
}

void CClearBitsDlg::OnDropFiles(HDROP hDropInfo) 
{
	SetForegroundWindow();      // activate us first !

	UINT nFiles = ::DragQueryFile(hDropInfo, (UINT)-1, NULL, 0);
	for (UINT iFile = 0; iFile < nFiles; iFile++)
	{
		CString strFilename;
		::DragQueryFile( hDropInfo, iFile, strFilename.GetBuffer(_MAX_PATH), _MAX_PATH );
		strFilename.ReleaseBuffer();

		if ( !strFilename.IsEmpty() && !AddToPlayList (strFilename) )
			AfxMessageBox ( _T("Error loading play list") );
	}
	
	::DragFinish(hDropInfo);
}

void CClearBitsDlg::OnButtonMove() 
{
	// Move the selected file
	int nSel = m_lbWaveFiles.GetCurSel();
	if ( (m_lbWaveFiles.GetCount() > 0) && (nSel >= 0))	// file is selected
	{
		// Ask for dest dir
		CBrowseDlg dlg (GetSafeHwnd(), _T("Destination folder"), COptions::m_strMoveDestDir);
		if ( dlg.DoModal() == IDOK )
		{
			// Save dest dir in COptions
			CString strDest = dlg.m_strDir;
			if ( strDest[strDest.GetLength() - 1] != '\\' )
				strDest += '\\';		// ensure strDest ends with "\" so we can append filename directly after it
			COptions::m_strMoveDestDir = strDest;


			// Get source file
			CString strCurFile;
			m_lbWaveFiles.GetText (nSel, strCurFile);

			// DC HACK:  Remove number at beginning
			if (isdigit(strCurFile[0]))
			{
				int iDot = strCurFile.Find ('.');
				if ( (iDot >= 0) && (iDot <= 4) )
					strCurFile = strCurFile.Mid ( iDot + 2 );
			}

			// Get dest file
			CFileName fnSource (strCurFile);
			strDest += fnSource.GetFile() + fnSource.GetExt();

			// Stop playback so file is not in use
			BOOL bIsPlaying = m_WaveReader.IsOpen();
			Stop();

			// move it
			if ( MoveFile (strCurFile, strDest) )
			{
				// delete from listbox
				m_lbWaveFiles.DeleteString (nSel);

				// Save playlist
				SavePlaylist();
			}
			else
			{
				CString strMsg;
				strMsg.Format ("Could not move\n%s to\n%s", (LPCTSTR) strCurFile, (LPCTSTR) strDest);
				AfxMessageBox (strMsg);
			}


			if (nSel >= m_lbWaveFiles.GetCount())
				nSel = m_lbWaveFiles.GetCount();

			if (nSel >= 0)	// valid selection
			{
				m_lbWaveFiles.SetCurSel (nSel);

				// Resume playback
				if (bIsPlaying)
					Play (TRUE);
			}
		}

		m_lbWaveFiles.SetFocus();
	}
}

BOOL CClearBitsDlg::OnQueryNewPalette() 
{
	m_LogoDibWnd.OnQueryNewPalette (GetSafeHwnd());
	return CDialog::OnQueryNewPalette();
}

void CClearBitsDlg::OnPaletteChanged(CWnd* pFocusWnd) 
{
	CDialog::OnPaletteChanged(pFocusWnd);
	m_LogoDibWnd.OnPaletteChanged (GetSafeHwnd(), (WPARAM) pFocusWnd);
}


void CClearBitsDlg::OnSize(UINT nType, int cx, int cy) 
{
	static RULE s_rules[] =
	{
		// Action    Act-on							Relative-to				Offset
		// ------    ------							-----------				------

		{  lMOVE,	 lRIGHT (IDC_STATIC_OUTPUT_FORMAT),		lRIGHT  (lPARENT),		-7  },
		{  lMOVE,	 lRIGHT (IDC_STATIC_PROGRESS),	lRIGHT  (lPARENT),		-7  },

		{  lMOVE,    lBOTTOM (IDC_STATIC_LOAD),		lBOTTOM (lPARENT),		-6  },
		{  lMOVE,    lBOTTOM (IDC_STATIC_CLEAR),	lBOTTOM (lPARENT),		-6  },
		{  lMOVE,    lBOTTOM (IDC_STATIC_DELETE),	lBOTTOM (lPARENT),		-6  },
		{  lMOVE,    lBOTTOM (IDC_STATIC_MOVEFILE),	lBOTTOM (lPARENT),		-6  },

		{  lMOVE,    lBOTTOM (IDC_CHECK_RANDOM),	lBOTTOM (lPARENT),		-6  },
		{  lMOVE,	 lRIGHT (IDC_CHECK_RANDOM),		lRIGHT  (lPARENT),		-7  },

		{  lSTRETCH, lRIGHT (IDC_LIST_WAVEFILES),   lRIGHT  (lPARENT),		-7  },
		{  lSTRETCH, lBOTTOM (IDC_LIST_WAVEFILES),  lTOP (IDC_CHECK_RANDOM),-2  },
		{  lEND															  		}
	};

	CDialog::OnSize(nType, cx, cy);
	
	if (GetSafeHwnd() && (cx > 0) && (cy > 0) )
	{
		// Place the dialog's child controls according to the rules. If there is
		// a problem with the rules, Layout_ComputeLayout will assert.
		Layout_ComputeLayout(GetSafeHwnd(), s_rules);
	}
}



void CClearBitsDlg::OnCbnSelchangeComboAlgo()
{
	SetAlgo ( m_cbAlgo.GetCurSel() );
}
