; This file can be edited to change the style of the application
; Read "Qt Quick Controls 2 Configuration File" for details:
; https://doc.qt.io/qt-6/qtquickcontrols-configuration.html

[Controls]
; A consistent Microsoft Fluent‑like look across platforms that matches WinUI 3 reasonably well
; it is not native, but it’s designed for Windows 11+ and can be tuned via palette and fonts.
Style=FluentWinUI3

[Universal]
Theme=System
